-- v121: move ACNC name_mission_embedding to a sibling table
-- `acnc_charity_embeddings`.
--
-- WHY: HNSW indexes on write-frequent tables blow the Disk-IO budget. The
-- 2026-05-09 incident saw the HNSW on acnc_charities (481 MB) help push
-- index pressure past sustainable IO during a single large UPDATE; the
-- index was manually dropped during remediation. This migration moves the
-- embedding column off the daily-written parent and onto a 1:1 sibling
-- whose only writes are when a new charity gets embedded — so future
-- HNSW maintenance no longer competes with the daily scraper UPDATE on
-- last_seen_in_register / source_row_hash / etc.
--
-- See:
--   CLAUDE.md  "Never Do" item #5 (large vector index on write-hot table)
--   v89        scam_reports/verified_scams embeddings sibling (precedent)
--   docs/plans/api-costs-caching-and-scale.md  §6.4
--
-- Cutover strategy (two PRs):
--   v121 (this) — create sibling, copy existing data, rewrite the RPC to
--                 JOIN the sibling, drop the parent HNSW. Parent column
--                 stays for rollback safety.
--   v122 (next PR, after cutover verified) — drop the now-redundant
--                                            acnc_charities.name_mission_embedding
--                                            column.
--
-- IDEMPOTENT: CREATE TABLE IF NOT EXISTS, CREATE INDEX IF NOT EXISTS,
-- DROP INDEX IF EXISTS, DROP POLICY IF EXISTS … CREATE POLICY, and the
-- backfill INSERT uses ON CONFLICT DO NOTHING.

-- ---------------------------------------------------------------------------
-- 1. Sibling table
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.acnc_charity_embeddings (
  charity_abn  TEXT PRIMARY KEY
               REFERENCES public.acnc_charities(abn) ON DELETE CASCADE,
  embedding    VECTOR(1024) NOT NULL,
  model        TEXT NOT NULL,
  embedded_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.acnc_charity_embeddings IS
  '1:1 sibling of acnc_charities for the name+other-names embedding. Split '
  'out from the parent in v121 so the HNSW index lives on a write-cold '
  'table — daily ACNC scraper UPDATEs on the parent no longer have to '
  'consider an HNSW index. ON DELETE CASCADE keeps the sibling in lockstep '
  'when a charity is hard-deleted (rare — usually they soft-delete via '
  'acnc_charities.is_delisted).';

COMMENT ON COLUMN public.acnc_charity_embeddings.embedding IS
  'voyage-3.5 (or whichever model `model` records) 1024-dim embedding of '
  'acnc_charities.charity_legal_name + other_names. Generated by the '
  'acnc-charity-backfill-embed Inngest function.';

COMMENT ON COLUMN public.acnc_charity_embeddings.model IS
  'EmbedResult.modelId at the time of embedding. Used by the reindex policy '
  '(ADR-0003) to find rows whose model is older than the current default.';

-- ---------------------------------------------------------------------------
-- 2. HNSW + model-version index on the sibling
-- ---------------------------------------------------------------------------

-- Same params as the old idx_acnc_name_mission_embedding_hnsw (m=16, ef=64
-- defaults) — the sibling is the same shape and size (~63k rows).
-- HNSW index on the embedding column.
--
-- DEFERRED TO OPERATOR-DRIVEN MAINTENANCE WINDOW.
-- Build via the Supabase SQL Editor (which has a longer query budget than
-- the MCP / migration runner) BEFORE flipping NEXT_PUBLIC_FF_CHARITY_CHECK
-- to true. At 63k × 1024-dim vectors the build takes ~10–15 min on
-- Pro-tier compute and exceeds the migration timeout. Without the index
-- the RPC `match_charities_by_embedding` falls back to a sequential scan
-- (~5s/query) — functional but too slow for a consumer surface.
--
-- Run this exact statement once via SQL Editor:
--
--   CREATE INDEX IF NOT EXISTS idx_acnc_charity_embeddings_hnsw
--     ON public.acnc_charity_embeddings
--     USING hnsw (embedding vector_cosine_ops);
--
-- See docs/ops/charity-check-config.md → "HNSW build (one-shot)".

CREATE INDEX IF NOT EXISTS idx_acnc_charity_embeddings_model
  ON public.acnc_charity_embeddings (model);

-- ---------------------------------------------------------------------------
-- 3. One-shot data migration from parent → sibling
--    Idempotent via ON CONFLICT (re-applying after partial run is safe).
-- ---------------------------------------------------------------------------

INSERT INTO public.acnc_charity_embeddings (charity_abn, embedding, model, embedded_at)
SELECT
  c.abn,
  c.name_mission_embedding,
  COALESCE(c.embedding_model_version, 'unknown'),
  COALESCE(c.updated_at, now())
FROM public.acnc_charities c
WHERE c.name_mission_embedding IS NOT NULL
ON CONFLICT (charity_abn) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 4. RLS — service-role writes; reads via SECURITY DEFINER RPC below
-- ---------------------------------------------------------------------------

ALTER TABLE public.acnc_charity_embeddings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS acnc_charity_embeddings_service_role
  ON public.acnc_charity_embeddings;
CREATE POLICY acnc_charity_embeddings_service_role
  ON public.acnc_charity_embeddings
  AS PERMISSIVE
  FOR ALL TO service_role
  USING (true) WITH CHECK (true);

-- ---------------------------------------------------------------------------
-- 5. Rewrite the consumer RPC to JOIN the sibling.
--    Signature unchanged (callers in packages/charity-check/ don't need to
--    update). DROP+CREATE so the body refresh sticks even if Postgres
--    treats CREATE OR REPLACE as a body-only update.
-- ---------------------------------------------------------------------------

DROP FUNCTION IF EXISTS public.match_charities_by_embedding(VECTOR(1024), INT, REAL);

CREATE FUNCTION public.match_charities_by_embedding(
  p_query_embedding VECTOR(1024),
  p_match_count     INT  DEFAULT 5,
  p_min_similarity  REAL DEFAULT 0.55
) RETURNS TABLE (
  abn                 TEXT,
  charity_legal_name  TEXT,
  charity_website     TEXT,
  town_city           TEXT,
  state               TEXT,
  similarity          REAL
)
LANGUAGE plpgsql STABLE
-- search_path must include `extensions` so pgvector's <=> operator resolves
-- (extensions were moved out of public in v103). See CLAUDE.md "PL/pgSQL
-- function gotchas" — extension-provided operators are the gotcha here.
SET search_path = public, extensions, pg_catalog
AS $$
#variable_conflict use_column
BEGIN
  PERFORM set_config('hnsw.ef_search', '80', true);

  RETURN QUERY
  SELECT
    c.abn,
    c.charity_legal_name,
    c.charity_website,
    c.town_city,
    c.state,
    (1 - (e.embedding <=> p_query_embedding))::REAL AS similarity
  FROM public.acnc_charity_embeddings e
  JOIN public.acnc_charities          c ON c.abn = e.charity_abn
  WHERE (1 - (e.embedding <=> p_query_embedding)) >= p_min_similarity
    AND COALESCE(c.is_delisted, false) = false
  ORDER BY e.embedding <=> p_query_embedding ASC
  LIMIT p_match_count;
END;
$$;

REVOKE ALL ON FUNCTION public.match_charities_by_embedding(VECTOR(1024), INT, REAL) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.match_charities_by_embedding(VECTOR(1024), INT, REAL)
  TO anon, authenticated, service_role;

COMMENT ON FUNCTION public.match_charities_by_embedding(VECTOR(1024), INT, REAL) IS
  'Cosine-similarity NN over acnc_charity_embeddings (sibling of '
  'acnc_charities, v121). Filters out is_delisted=true charities so a '
  'delisted rogue cannot match. Caller should embed the query with '
  'embedQuery(_, { domain: "generic" }) so the asymmetric Voyage prompt '
  'aligns with how documents were embedded.';

-- ---------------------------------------------------------------------------
-- 6. Helper RPC for the backfill Inngest function — load charities that
--    don't yet have a sibling embedding row. Replaces the old
--    `IS NULL` filter on the parent column.
-- ---------------------------------------------------------------------------

DROP FUNCTION IF EXISTS public.get_acnc_charities_missing_embedding(INT);

CREATE FUNCTION public.get_acnc_charities_missing_embedding(
  p_limit INT DEFAULT 200
) RETURNS TABLE (
  abn                 TEXT,
  charity_legal_name  TEXT,
  other_names         TEXT[]
)
LANGUAGE sql STABLE
SET search_path = public, pg_catalog
AS $$
  SELECT c.abn, c.charity_legal_name, c.other_names
  FROM   public.acnc_charities c
  WHERE  NOT EXISTS (
           SELECT 1 FROM public.acnc_charity_embeddings e
           WHERE  e.charity_abn = c.abn
         )
    AND  COALESCE(c.is_delisted, false) = false
    AND  c.charity_legal_name IS NOT NULL
  ORDER BY c.abn ASC
  LIMIT p_limit;
$$;

REVOKE ALL ON FUNCTION public.get_acnc_charities_missing_embedding(INT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_acnc_charities_missing_embedding(INT)
  TO service_role;

COMMENT ON FUNCTION public.get_acnc_charities_missing_embedding(INT) IS
  'Backfill helper for acnc-charity-backfill-embed Inngest function. Loads '
  'live (non-delisted) ACNC charities whose row is absent from the sibling '
  'embeddings table. Idempotent — re-running drops rows already covered.';

-- ---------------------------------------------------------------------------
-- 7. Drop the now-orphaned indexes on the parent column. The 2026-05-09
--    incident already manually dropped these, so this is a no-op in
--    production, but keeping them in the migration makes the post-state
--    explicit and ensures re-applying on a fresh restore lands clean.
-- ---------------------------------------------------------------------------

DROP INDEX IF EXISTS public.idx_acnc_name_mission_embedding_hnsw;
DROP INDEX IF EXISTS public.idx_acnc_embedding_model_version;
