-- v174 — canonical brand-alias layer  (branch: partner-data/brand-alias-layer)
--
-- WHY: brand-name is the single least-reliable join in the platform. The same
-- real-world brand appears as free text across scam_reports.impersonated_brand,
-- feed_items.impersonated_brand, reddit_post_intel.brands_impersonated[],
-- brand_contact_directory.brand and clone-watch's shopfront_clone_alerts.brand —
-- "NAB" vs "nab" vs "National Australia Bank" never join. Every brand-grouped
-- partner product (the monthly per-brand clone dossier, a bank-routable feed)
-- rests on this join. This migration adds a canonical alias->brand lookup plus a
-- normalize/resolve function pair so any free-text brand mention resolves to ONE
-- canonical brand.
--
-- SCOPE: purely additive — a new reference table + two functions + seed data.
-- No existing table is altered; no write path changes; the entity write path
-- (report_scam_entity, v170) and clone-watch are untouched. Reference data only,
-- service-role read (matches brand_contact_directory, v143). Idempotent.
--
-- NOT IN THIS MIGRATION: scam_entities provenance columns (regulator_confirmed /
-- source_tier / confidence). report_scam_entity (v170) has no source column, so
-- a correct backfill needs a write-path change — that ships with the bank-URL-
-- feed product PR that consumes those columns, keeping THIS PR zero-impact.
--
-- ROLLBACK (run manually if ever needed — no data depends on this yet):
--   DROP FUNCTION IF EXISTS public.resolve_brand(text);
--   DROP TABLE    IF EXISTS public.brand_aliases;
--   DROP FUNCTION IF EXISTS public.brand_normalize(text);

-- 1. Normalization: lowercase + strip everything but [a-z0-9]. IMMUTABLE (can
--    back an expression index later) with a pinned search_path (no advisor
--    WARN). Uses only pg_catalog built-ins.
CREATE OR REPLACE FUNCTION public.brand_normalize(p_raw text)
RETURNS text
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
SET search_path = pg_catalog
AS $$
  SELECT NULLIF(regexp_replace(lower(coalesce(p_raw, '')), '[^a-z0-9]+', '', 'g'), '');
$$;

COMMENT ON FUNCTION public.brand_normalize(text) IS
  'Canonicalises a free-text brand string to a join key: lowercase + strip non-alphanumerics. Returns NULL for empty/whitespace-only input. v174.';

-- 2. Alias -> canonical-brand lookup. alias_normalized is the join key.
CREATE TABLE IF NOT EXISTS public.brand_aliases (
  alias_normalized text PRIMARY KEY,
  canonical_brand  text NOT NULL,
  source           text NOT NULL DEFAULT 'manual'
    CHECK (source IN ('watchlist', 'directory', 'manual')),
  created_at       timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_brand_aliases_canonical
  ON public.brand_aliases (canonical_brand);

COMMENT ON TABLE public.brand_aliases IS
  'Canonical brand-alias layer: maps a normalized brand token (alias_normalized = brand_normalize(raw)) to one canonical_brand. Seeded from au-brand-watchlist.ts + brand_contact_directory; curated rows use source=manual. Re-seeding the watchlist is a NEW migration, never an edit to this one. Service-role only. v174.';

ALTER TABLE public.brand_aliases ENABLE ROW LEVEL SECURITY;
-- No policies = service_role only (anon/authed get nothing), matching
-- brand_contact_directory (v143). Non-sensitive, but no client needs it.

-- 3. Resolver: free-text brand -> canonical_brand (NULL if unknown). STABLE
--    (reads a table); SECURITY INVOKER — every consumer is service_role
--    (Inngest fns, dashboard libs) which bypasses RLS. An anon caller sees an
--    empty table and gets NULL, so no leak. EXECUTE locked down (v160 lesson:
--    Supabase auto-grants EXECUTE to PUBLIC; per-role revoke alone is a no-op).
CREATE OR REPLACE FUNCTION public.resolve_brand(p_raw text)
RETURNS text
LANGUAGE sql
STABLE
SET search_path = ''
AS $$
  SELECT ba.canonical_brand
  FROM public.brand_aliases ba
  WHERE ba.alias_normalized = public.brand_normalize(p_raw);
$$;

COMMENT ON FUNCTION public.resolve_brand(text) IS
  'Resolves a free-text brand mention to its canonical_brand via brand_aliases, or NULL if unrecognised. The read-side primitive for brand-grouped partner products. v174.';

REVOKE EXECUTE ON FUNCTION public.resolve_brand(text) FROM PUBLIC, anon, authenticated;
GRANT  EXECUTE ON FUNCTION public.resolve_brand(text) TO service_role;

-- 4a. Seed from au-brand-watchlist.ts (generated by scripts/gen-brand-aliases-seed.mjs;
--     223 rows: 214 brands + their short-form aliases). ON CONFLICT
--     DO NOTHING keeps re-apply idempotent and never clobbers a curated manual row.
INSERT INTO public.brand_aliases (alias_normalized, canonical_brand, source) VALUES
  ('7eleven', '7-Eleven', 'watchlist'),
  ('aami', 'AAMI', 'watchlist'),
  ('afterpay', 'Afterpay', 'watchlist'),
  ('agl', 'AGL', 'watchlist'),
  ('ahm', 'AHM', 'watchlist'),
  ('airwallex', 'Airwallex', 'watchlist'),
  ('aldi', 'Aldi', 'watchlist'),
  ('alintaenergy', 'Alinta Energy', 'watchlist'),
  ('allianz', 'Allianz', 'watchlist'),
  ('amaysim', 'Amaysim', 'watchlist'),
  ('amp', 'AMP', 'watchlist'),
  ('anz', 'ANZ', 'watchlist'),
  ('athenahomeloans', 'Athena Home Loans', 'watchlist'),
  ('auspost', 'Australia Post', 'watchlist'),
  ('aussiebroadband', 'Aussie Broadband', 'watchlist'),
  ('aussiehomeloans', 'Aussie Home Loans', 'watchlist'),
  ('australianelectoralcommission', 'Australian Electoral Commission', 'watchlist'),
  ('australianethical', 'Australian Ethical', 'watchlist'),
  ('australianmilitarybank', 'Australian Military Bank', 'watchlist'),
  ('australianretirementtrust', 'Australian Retirement Trust', 'watchlist'),
  ('australiansuper', 'AustralianSuper', 'watchlist'),
  ('australiantaxationoffice', 'Australian Taxation Office', 'watchlist'),
  ('australiapost', 'Australia Post', 'watchlist'),
  ('awaresuper', 'Aware Super', 'watchlist'),
  ('banjoloans', 'Banjo Loans', 'watchlist'),
  ('bankaust', 'Bank Australia', 'watchlist'),
  ('bankaustralia', 'Bank Australia', 'watchlist'),
  ('bankofmelbourne', 'Bank of Melbourne', 'watchlist'),
  ('bankofqueensland', 'Bank of Queensland', 'watchlist'),
  ('banksa', 'BankSA', 'watchlist'),
  ('bankwest', 'Bankwest', 'watchlist'),
  ('beem', 'Beem', 'watchlist'),
  ('beforepay', 'Beforepay', 'watchlist'),
  ('belong', 'Belong', 'watchlist'),
  ('bendigobank', 'Bendigo Bank', 'watchlist'),
  ('beyondbank', 'Beyond Bank', 'watchlist'),
  ('bigstone', 'Bigstone', 'watchlist'),
  ('bigw', 'Big W', 'watchlist'),
  ('binanceaustralia', 'Binance Australia', 'watchlist'),
  ('bonds', 'Bonds', 'watchlist'),
  ('bookingcom', 'Booking.com', 'watchlist'),
  ('boostmobile', 'Boost Mobile', 'watchlist'),
  ('boq', 'Bank of Queensland', 'watchlist'),
  ('bpay', 'BPAY', 'watchlist'),
  ('btcmarkets', 'BTC Markets', 'watchlist'),
  ('budgetdirect', 'Budget Direct', 'watchlist'),
  ('bunnings', 'Bunnings', 'watchlist'),
  ('bupa', 'Bupa', 'watchlist'),
  ('bws', 'BWS', 'watchlist'),
  ('carsales', 'Carsales', 'watchlist'),
  ('cashconverters', 'Cash Converters', 'watchlist'),
  ('cba', 'CBA', 'watchlist'),
  ('cbus', 'Cbus', 'watchlist'),
  ('cfs', 'Colonial First State', 'watchlist'),
  ('chemistwarehouse', 'Chemist Warehouse', 'watchlist'),
  ('citybeach', 'City Beach', 'watchlist'),
  ('coinspot', 'CoinSpot', 'watchlist'),
  ('coles', 'Coles', 'watchlist'),
  ('colonialfirststate', 'Colonial First State', 'watchlist'),
  ('commbank', 'CBA', 'watchlist'),
  ('commsec', 'CommSec', 'watchlist'),
  ('cottonon', 'Cotton On', 'watchlist'),
  ('countryroad', 'Country Road', 'watchlist'),
  ('danmurphys', 'Dan Murphy''s', 'watchlist'),
  ('davidjones', 'David Jones', 'watchlist'),
  ('departmentofhomeaffairs', 'Department of Home Affairs', 'watchlist'),
  ('digitalsurge', 'Digital Surge', 'watchlist'),
  ('disneyau', 'Disney+ (AU)', 'watchlist'),
  ('dodo', 'Dodo', 'watchlist'),
  ('domain', 'Domain', 'watchlist'),
  ('dominos', 'Domino''s', 'watchlist'),
  ('eastlink', 'EastLink', 'watchlist'),
  ('ebayaustralia', 'eBay Australia', 'watchlist'),
  ('energyaustralia', 'EnergyAustralia', 'watchlist'),
  ('exetel', 'Exetel', 'watchlist'),
  ('facebook', 'Facebook', 'watchlist'),
  ('felixmobile', 'Felix Mobile', 'watchlist'),
  ('firefightersmutualbank', 'Firefighters Mutual Bank', 'watchlist'),
  ('firstmac', 'Firstmac', 'watchlist'),
  ('flightcentre', 'Flight Centre', 'watchlist'),
  ('foxtelkayo', 'Foxtel / Kayo', 'watchlist'),
  ('gio', 'GIO', 'watchlist'),
  ('gluestore', 'Glue Store', 'watchlist'),
  ('greaterbank', 'Greater Bank', 'watchlist'),
  ('greatsouthernbank', 'Great Southern Bank', 'watchlist'),
  ('gumtree', 'Gumtree', 'watchlist'),
  ('harmoney', 'Harmoney', 'watchlist'),
  ('harveynorman', 'Harvey Norman', 'watchlist'),
  ('hbf', 'HBF', 'watchlist'),
  ('hcf', 'HCF', 'watchlist'),
  ('healthprofessionalsbank', 'Health Professionals Bank', 'watchlist'),
  ('heritagebank', 'Heritage Bank', 'watchlist'),
  ('hesta', 'HESTA', 'watchlist'),
  ('hostplus', 'Hostplus', 'watchlist'),
  ('humm', 'Humm', 'watchlist'),
  ('hungryjacks', 'Hungry Jack''s', 'watchlist'),
  ('iga', 'IGA', 'watchlist'),
  ('iinet', 'iiNet', 'watchlist'),
  ('independentreserve', 'Independent Reserve', 'watchlist'),
  ('ingaustralia', 'ING Australia', 'watchlist'),
  ('ingdirect', 'ING Australia', 'watchlist'),
  ('instagram', 'Instagram', 'watchlist'),
  ('jbhifi', 'JB Hi-Fi', 'watchlist'),
  ('jetstar', 'Jetstar', 'watchlist'),
  ('judobank', 'Judo Bank', 'watchlist'),
  ('kfc', 'KFC', 'watchlist'),
  ('klarna', 'Klarna', 'watchlist'),
  ('kmart', 'Kmart', 'watchlist'),
  ('kogan', 'Kogan', 'watchlist'),
  ('koganmobile', 'Kogan Mobile', 'watchlist'),
  ('latitudefinancial', 'Latitude Financial', 'watchlist'),
  ('latrobefinancial', 'La Trobe Financial', 'watchlist'),
  ('lendi', 'Lendi', 'watchlist'),
  ('libertyfinancial', 'Liberty Financial', 'watchlist'),
  ('linkttransurban', 'Linkt (Transurban)', 'watchlist'),
  ('liquorland', 'Liquorland', 'watchlist'),
  ('loanscomau', 'loans.com.au', 'watchlist'),
  ('lumi', 'Lumi', 'watchlist'),
  ('macquarie', 'Macquarie Bank', 'watchlist'),
  ('macquariebank', 'Macquarie Bank', 'watchlist'),
  ('mcdonalds', 'McDonald''s', 'watchlist'),
  ('mebank', 'ME Bank', 'watchlist'),
  ('medibank', 'Medibank', 'watchlist'),
  ('mitre10', 'Mitre 10', 'watchlist'),
  ('mlc', 'MLC', 'watchlist'),
  ('moneyme', 'MoneyMe', 'watchlist'),
  ('moosemobile', 'Moose Mobile', 'watchlist'),
  ('mortgagechoice', 'Mortgage Choice', 'watchlist'),
  ('moula', 'Moula', 'watchlist'),
  ('mydeal', 'MyDeal', 'watchlist'),
  ('myer', 'Myer', 'watchlist'),
  ('mygov', 'myGov', 'watchlist'),
  ('mykipublictransportvictoria', 'myki (Public Transport Victoria)', 'watchlist'),
  ('nab', 'NAB', 'watchlist'),
  ('ndis', 'NDIS', 'watchlist'),
  ('netflixau', 'Netflix (AU)', 'watchlist'),
  ('newcastlepermanent', 'Newcastle Permanent', 'watchlist'),
  ('nib', 'NIB', 'watchlist'),
  ('nimble', 'Nimble', 'watchlist'),
  ('nrma', 'NRMA', 'watchlist'),
  ('officeworks', 'Officeworks', 'watchlist'),
  ('ondeck', 'OnDeck', 'watchlist'),
  ('opaltransportfornsw', 'Opal (Transport for NSW)', 'watchlist'),
  ('optus', 'Optus', 'watchlist'),
  ('originenergy', 'Origin Energy', 'watchlist'),
  ('paypal', 'PayPal', 'watchlist'),
  ('pearler', 'Pearler', 'watchlist'),
  ('peoplefirstbank', 'People First Bank', 'watchlist'),
  ('peppermoney', 'Pepper Money', 'watchlist'),
  ('pnbank', 'P&N Bank', 'watchlist'),
  ('policebank', 'Police Bank', 'watchlist'),
  ('powershop', 'Powershop', 'watchlist'),
  ('priceline', 'Priceline', 'watchlist'),
  ('prospa', 'Prospa', 'watchlist'),
  ('qantas', 'Qantas', 'watchlist'),
  ('qbe', 'QBE', 'watchlist'),
  ('qudosbank', 'Qudos Bank', 'watchlist'),
  ('racq', 'RACQ', 'watchlist'),
  ('racv', 'RACV', 'watchlist'),
  ('raiz', 'Raiz', 'watchlist'),
  ('realestatecomau', 'realestate.com.au', 'watchlist'),
  ('redenergy', 'Red Energy', 'watchlist'),
  ('reece', 'Reece', 'watchlist'),
  ('reservebankofaustralia', 'Reserve Bank of Australia', 'watchlist'),
  ('resimac', 'Resimac', 'watchlist'),
  ('restsuper', 'REST Super', 'watchlist'),
  ('revolut', 'Revolut', 'watchlist'),
  ('selfwealth', 'SelfWealth', 'watchlist'),
  ('sendle', 'Sendle', 'watchlist'),
  ('servicensw', 'Service NSW', 'watchlist'),
  ('servicesaustralia', 'Services Australia', 'watchlist'),
  ('servicevictoria', 'Service Victoria', 'watchlist'),
  ('servicewa', 'Service WA', 'watchlist'),
  ('simplyenergy', 'Simply Energy', 'watchlist'),
  ('smiggle', 'Smiggle', 'watchlist'),
  ('southernphone', 'Southern Phone', 'watchlist'),
  ('spaceship', 'Spaceship', 'watchlist'),
  ('spintel', 'SpinTel', 'watchlist'),
  ('sportsgirl', 'Sportsgirl', 'watchlist'),
  ('spotifyau', 'Spotify (AU)', 'watchlist'),
  ('stake', 'Stake', 'watchlist'),
  ('stan', 'Stan', 'watchlist'),
  ('startrack', 'StarTrack', 'watchlist'),
  ('stgeorge', 'St.George Bank', 'watchlist'),
  ('stgeorgebank', 'St.George Bank', 'watchlist'),
  ('subway', 'Subway', 'watchlist'),
  ('suncorp', 'Suncorp', 'watchlist'),
  ('superhero', 'Superhero', 'watchlist'),
  ('superloop', 'Superloop', 'watchlist'),
  ('surfstitch', 'Surfstitch', 'watchlist'),
  ('swyftx', 'Swyftx', 'watchlist'),
  ('tangerine', 'Tangerine', 'watchlist'),
  ('target', 'Target', 'watchlist'),
  ('teachersmutualbank', 'Teachers Mutual Bank', 'watchlist'),
  ('telstra', 'Telstra', 'watchlist'),
  ('tiimelyhome', 'Tiimely Home', 'watchlist'),
  ('tmbank', 'Teachers Mutual Bank', 'watchlist'),
  ('toll', 'Toll', 'watchlist'),
  ('toyworld', 'Toyworld', 'watchlist'),
  ('tpg', 'TPG', 'watchlist'),
  ('translinkqueensland', 'Translink (Queensland)', 'watchlist'),
  ('ubank', 'Ubank', 'watchlist'),
  ('unibank', 'UniBank', 'watchlist'),
  ('unisuper', 'UniSuper', 'watchlist'),
  ('unitybank', 'Unity Bank', 'watchlist'),
  ('universalstore', 'Universal Store', 'watchlist'),
  ('unloan', 'Unloan', 'watchlist'),
  ('upbank', 'Up Bank', 'watchlist'),
  ('valiantfinance', 'Valiant Finance', 'watchlist'),
  ('vervesuper', 'Verve Super', 'watchlist'),
  ('virginaustralia', 'Virgin Australia', 'watchlist'),
  ('virginmoney', 'Virgin Money', 'watchlist'),
  ('vodafone', 'Vodafone', 'watchlist'),
  ('webjet', 'Webjet', 'watchlist'),
  ('westpac', 'Westpac', 'watchlist'),
  ('wise', 'Wise', 'watchlist'),
  ('wisr', 'Wisr', 'watchlist'),
  ('witchery', 'Witchery', 'watchlist'),
  ('woolworths', 'Woolworths', 'watchlist'),
  ('wotif', 'Wotif', 'watchlist'),
  ('youi', 'Youi', 'watchlist'),
  ('zeller', 'Zeller', 'watchlist'),
  ('zip', 'Zip', 'watchlist')
ON CONFLICT (alias_normalized) DO NOTHING;

-- 4b. Seed every brand_contact_directory brand to itself, covering any directory
--     brand not on the watchlist. Dynamic so directory rows need no hardcoding.
INSERT INTO public.brand_aliases (alias_normalized, canonical_brand, source)
SELECT public.brand_normalize(d.brand), d.brand, 'directory'
FROM public.brand_contact_directory d
WHERE public.brand_normalize(d.brand) IS NOT NULL
ON CONFLICT (alias_normalized) DO NOTHING;
