// XMP / EXIF "claimed AI origin" detection — dependency-free.
//
// Scope (deliberate, sibling of c2pa-detect.ts): reads the CLAIMED tier of
// the AI-origin ladder — plain metadata tags that generators write but anyone
// can edit or strip. This is one rung below Content Credentials: a C2PA
// manifest is cryptographically signed; these tags are hints. Copy derived
// from this signal must present it as a claim ("tags like this can be
// edited"), never as verification — and absence of a tag says NOTHING about
// how an image was made (most platforms strip metadata on upload).
//
// Like c2pa-detect, detection is a structural container walk over exactly
// the formats validateImageMagicBytes admits (JPEG / PNG / WebP; GIF has no
// meaningful XMP/EXIF convention and reports no claim). A general-purpose
// metadata library (exifr etc.) is deliberately NOT used: these bytes are
// attacker-controlled, and a ~200-line targeted walk is less parser surface
// than a full EXIF/XMP/IPTC parser, with identical yield for the two fields
// we read:
// - XMP packet → IPTC DigitalSourceType (the industry-standard AI-origin
//   vocabulary; "trainedAlgorithmicMedia" = generated by AI) and
//   xmp:CreatorTool.
// - EXIF IFD0 tag 0x0131 (Software).
// A claim fires when DigitalSourceType carries a trained-media term, or when
// CreatorTool/Software names a known AI generator. "Adobe Photoshop" alone
// is NOT a claim — legitimate editors write these fields too.

export interface MetadataOriginDetection {
  /** True when metadata explicitly claims AI origin. Forgeable either way. */
  claimed: boolean;
  /** Where the claim was found — only set when claimed. */
  source?: "xmp" | "exif";
  /** Canonical generator name when CreatorTool/Software matched a known AI
   *  tool — display-ready ("Adobe Firefly"), null otherwise. */
  generator?: string | null;
  /** Raw IPTC DigitalSourceType term when present (any value — includes
   *  non-AI terms like "digitalCapture"), null when absent. */
  digitalSourceType?: string | null;
}

// IPTC digital-source-type vocabulary terms that constitute an AI claim.
// https://cv.iptc.org/newscodes/digitalsourcetype/
const TRAINED_MEDIA_TERMS = new Set([
  "trainedalgorithmicmedia",
  "compositewithtrainedalgorithmicmedia",
]);

// Known AI-generator names as they appear in CreatorTool / Software fields.
// Word-boundary anchored; keep conservative — a false "claims AI origin" on
// an editor string is worse than a miss.
const AI_GENERATOR_PATTERNS: Array<{ re: RegExp; name: string }> = [
  { re: /midjourney/i, name: "Midjourney" },
  { re: /dall[·\-. ]?e/i, name: "OpenAI DALL·E" },
  { re: /\bchatgpt\b|\bgpt-image\b/i, name: "OpenAI ChatGPT" },
  { re: /firefly/i, name: "Adobe Firefly" },
  { re: /stable ?diffusion|\bsdxl\b|stability ?ai/i, name: "Stable Diffusion" },
  { re: /\bimagen\b/i, name: "Google Imagen" },
  { re: /\bgemini\b/i, name: "Google Gemini" },
  { re: /ideogram/i, name: "Ideogram" },
  { re: /leonardo\.? ?ai/i, name: "Leonardo AI" },
  { re: /recraft/i, name: "Recraft" },
  { re: /black ?forest|flux\.?1/i, name: "FLUX" },
  { re: /\bgrok\b/i, name: "Grok" },
  { re: /bing image creator|microsoft designer/i, name: "Microsoft Designer" },
  { re: /canva magic|magic media/i, name: "Canva Magic Media" },
  { re: /\bclaude\b|anthropic/i, name: "Anthropic Claude" },
  { re: /\bsora\b/i, name: "OpenAI Sora" },
];

const XMP_JPEG_HEADER = "http://ns.adobe.com/xap/1.0/\0";
const EXIF_JPEG_HEADER = "Exif\0\0";

// ---------- container walks (mirror c2pa-detect's early-stop discipline) ----

function forEachJpegSegment(
  buf: Buffer,
  cb: (marker: number, payload: Buffer) => boolean | undefined,
): void {
  let pos = 2;
  while (pos + 4 <= buf.length) {
    if (buf[pos] !== 0xff) return;
    let markerPos = pos + 1;
    while (markerPos < buf.length && buf[markerPos] === 0xff) markerPos++;
    if (markerPos >= buf.length) return;
    const marker = buf[markerPos];
    if (marker === 0x01 || (marker >= 0xd0 && marker <= 0xd7)) {
      pos = markerPos + 1;
      continue;
    }
    if (marker === 0xda || marker === 0xd9) return; // SOS / EOI
    if (markerPos + 3 > buf.length) return;
    const length = buf.readUInt16BE(markerPos + 1);
    if (length < 2) return;
    const segEnd = markerPos + 1 + length;
    if (segEnd > buf.length) return; // truncated
    if (cb(marker, buf.subarray(markerPos + 3, segEnd))) return;
    pos = segEnd;
  }
}

function forEachPngChunk(
  buf: Buffer,
  cb: (type: string, data: Buffer) => boolean | undefined,
): void {
  let pos = 8;
  while (pos + 8 <= buf.length) {
    const length = buf.readUInt32BE(pos);
    const type = buf.subarray(pos + 4, pos + 8).toString("ascii");
    const next = pos + 8 + length + 4;
    if (next <= pos || next > buf.length) return;
    if (cb(type, buf.subarray(pos + 8, pos + 8 + length))) return;
    if (type === "IEND") return;
    pos = next;
  }
}

function forEachWebpChunk(
  buf: Buffer,
  cb: (fourCC: string, data: Buffer) => boolean | undefined,
): void {
  if (buf.length < 12 || buf.subarray(8, 12).toString("ascii") !== "WEBP") return;
  let pos = 12;
  while (pos + 8 <= buf.length) {
    const fourCC = buf.subarray(pos, pos + 4).toString("ascii");
    const size = buf.readUInt32LE(pos + 4);
    const next = pos + 8 + size + (size % 2);
    if (next <= pos || next > buf.length) return;
    if (cb(fourCC, buf.subarray(pos + 8, pos + 8 + size))) return;
    pos = next;
  }
}

// ---------- XMP packet extraction ------------------------------------------

function extractXmp(buf: Buffer): string | null {
  let xmp: string | null = null;
  if (isJpeg(buf)) {
    const header = Buffer.from(XMP_JPEG_HEADER, "ascii");
    forEachJpegSegment(buf, (marker, payload) => {
      // APP1 carrying the XMP namespace header. (Multi-segment ExtendedXMP
      // is not reassembled — the fields we read live in the main packet.)
      if (marker === 0xe1 && payload.subarray(0, header.length).equals(header)) {
        xmp = payload.subarray(header.length).toString("utf8");
        return true;
      }
      return undefined;
    });
  } else if (isPng(buf)) {
    forEachPngChunk(buf, (type, data) => {
      if (type !== "iTXt") return undefined;
      // iTXt: keyword\0 compressionFlag(1) compressionMethod(1) lang\0
      // translatedKeyword\0 text. XMP is spec-required to be uncompressed.
      const kwEnd = data.indexOf(0);
      if (kwEnd < 0 || data.subarray(0, kwEnd).toString("ascii") !== "XML:com.adobe.xmp") {
        return undefined;
      }
      if (data[kwEnd + 1] !== 0) return true; // compressed — spec violation, skip
      let p = kwEnd + 3;
      const langEnd = data.indexOf(0, p);
      if (langEnd < 0) return true;
      const tkEnd = data.indexOf(0, langEnd + 1);
      if (tkEnd < 0) return true;
      xmp = data.subarray(tkEnd + 1).toString("utf8");
      return true;
    });
  } else if (isWebp(buf)) {
    forEachWebpChunk(buf, (fourCC, data) => {
      if (fourCC !== "XMP ") return undefined;
      xmp = data.toString("utf8");
      return true;
    });
  }
  return xmp;
}

// ---------- EXIF Software (TIFF IFD0 tag 0x0131) ---------------------------

function parseTiffSoftware(tiff: Buffer): string | null {
  if (tiff.length < 8) return null;
  const bo = tiff.toString("ascii", 0, 2);
  const le = bo === "II";
  if (!le && bo !== "MM") return null;
  const r16 = (o: number): number => (le ? tiff.readUInt16LE(o) : tiff.readUInt16BE(o));
  const r32 = (o: number): number => (le ? tiff.readUInt32LE(o) : tiff.readUInt32BE(o));
  if (r16(2) !== 42) return null;
  const ifd = r32(4);
  if (ifd + 2 > tiff.length) return null;
  const n = r16(ifd);
  for (let i = 0; i < n; i++) {
    const entry = ifd + 2 + i * 12;
    if (entry + 12 > tiff.length) return null;
    if (r16(entry) !== 0x0131) continue; // Software
    if (r16(entry + 2) !== 2) return null; // must be ASCII
    const count = r32(entry + 4);
    if (count === 0 || count > 1024) return null;
    const valOff = count <= 4 ? entry + 8 : r32(entry + 8);
    if (valOff + count > tiff.length) return null;
    const value = tiff
      .toString("ascii", valOff, valOff + count)
      .replace(/\0+$/, "")
      .trim();
    return value.length > 0 ? value : null;
  }
  return null;
}

function extractExifSoftware(buf: Buffer): string | null {
  let software: string | null = null;
  if (isJpeg(buf)) {
    const header = Buffer.from(EXIF_JPEG_HEADER, "ascii");
    forEachJpegSegment(buf, (marker, payload) => {
      if (marker === 0xe1 && payload.subarray(0, header.length).equals(header)) {
        software = parseTiffSoftware(payload.subarray(header.length));
        return true;
      }
      return undefined;
    });
  } else if (isPng(buf)) {
    forEachPngChunk(buf, (type, data) => {
      if (type !== "eXIf") return undefined;
      software = parseTiffSoftware(data); // eXIf holds raw TIFF
      return true;
    });
  } else if (isWebp(buf)) {
    forEachWebpChunk(buf, (fourCC, data) => {
      if (fourCC !== "EXIF") return undefined;
      // Some encoders prefix the TIFF block with "Exif\0\0"; both occur.
      const prefixed = data.subarray(0, 6).toString("ascii") === EXIF_JPEG_HEADER;
      software = parseTiffSoftware(prefixed ? data.subarray(6) : data);
      return true;
    });
  }
  return software;
}

// ---------- field interpretation -------------------------------------------

/** Pull the IPTC DigitalSourceType term out of an XMP packet. Handles the
 *  attribute form, the element form, and the rdf:resource form. */
function xmpDigitalSourceType(xmp: string): string | null {
  const uri = xmp.match(
    /cv\.iptc\.org\/newscodes\/digitalsourcetype\/([A-Za-z]+)/,
  );
  if (uri) return uri[1];
  const el = xmp.match(
    /DigitalSourceType\s*(?:=\s*"([^"]+)"|>\s*([^<\s][^<]*?)\s*<)/i,
  );
  const raw = el?.[1] ?? el?.[2] ?? null;
  if (!raw) return null;
  const tail = raw.match(/([A-Za-z]+)\s*$/);
  return tail ? tail[1] : raw;
}

function xmpCreatorTool(xmp: string): string | null {
  const m = xmp.match(
    /(?:xmp|xap):CreatorTool\s*(?:=\s*"([^"]+)"|>\s*([^<]+?)\s*<)/i,
  );
  return m?.[1] ?? m?.[2] ?? null;
}

function matchAiGenerator(tool: string | null): string | null {
  if (!tool) return null;
  for (const { re, name } of AI_GENERATOR_PATTERNS) {
    if (re.test(tool)) return name;
  }
  return null;
}

const isJpeg = (b: Buffer): boolean =>
  b.length >= 3 && b[0] === 0xff && b[1] === 0xd8 && b[2] === 0xff;
const isPng = (b: Buffer): boolean =>
  b.length >= 8 && b[0] === 0x89 && b.subarray(1, 4).toString("ascii") === "PNG";
const isWebp = (b: Buffer): boolean =>
  b.length >= 4 && b.subarray(0, 4).toString("ascii") === "RIFF";

/**
 * Detect a CLAIMED AI origin in image metadata (XMP DigitalSourceType /
 * CreatorTool, EXIF Software). Never throws; unknown containers and
 * malformed/truncated files report {claimed: false}. Callers must treat
 * {claimed: false} as "no tag found", never as "not AI" — and pass null
 * (not this function's output) when bytes were unavailable.
 */
export function detectMetadataOrigin(buf: Buffer): MetadataOriginDetection {
  try {
    const xmp = extractXmp(buf);
    const digitalSourceType = xmp ? xmpDigitalSourceType(xmp) : null;
    const creatorTool = xmp ? xmpCreatorTool(xmp) : null;

    if (digitalSourceType && TRAINED_MEDIA_TERMS.has(digitalSourceType.toLowerCase())) {
      return {
        claimed: true,
        source: "xmp",
        generator: matchAiGenerator(creatorTool),
        digitalSourceType,
      };
    }

    const xmpGenerator = matchAiGenerator(creatorTool);
    if (xmpGenerator) {
      return { claimed: true, source: "xmp", generator: xmpGenerator, digitalSourceType };
    }

    const exifGenerator = matchAiGenerator(extractExifSoftware(buf));
    if (exifGenerator) {
      return { claimed: true, source: "exif", generator: exifGenerator, digitalSourceType };
    }

    return { claimed: false, generator: null, digitalSourceType };
  } catch {
    return { claimed: false, generator: null, digitalSourceType: null };
  }
}
